FROM node:18.17.1-bullseye-slim

WORKDIR /client

RUN apt update \
  && yarn install

COPY . /client
COPY package.json /client/package.json
COPY yarn.lock /client/yarn.lock

EXPOSE 8080
CMD ["yarn", "dev", "--host"]