# ユーザー登録
POST http://localhost:3000/api/v1/auth 
Content-Type: application/json

{
  "name": "test_user",
  "email": "example@example.com",
  "password": "password",
  "password_confirmation": "password"
}

###

# サインイン
POST http://localhost:3000/api/v1/auth/sign_in
Content-Type: application/json

{
  "name": "test_user",
  "email": "example@example.com",
  "password": "password",
  "password_confirmation": "password"
}

###

# サインアウト
DELETE http://localhost:3000/api/v1/auth/sign_out
Content-Type: application/json

{
  "uid": "example@example.com",
  "client": "UMFPpMZUZ0_eWVRm6tPBtg",
  "access-token": "j9bmoMhGWscI6BnX5vHDVg"
}
